In [67]:
import torch
from torch.nn import functional as F
torch.__version__

'2.0.1'

In [4]:
a = torch.rand(4,3,32,32)
b = torch.rand(1,1,32,1)

In [11]:
b.repeat(4,1,64,1).shape


torch.Size([4, 1, 2048, 1])

In [12]:
a.transpose(1,3).shape

torch.Size([4, 32, 32, 3])

In [13]:
a.permute(0,2,3,1).shape

torch.Size([4, 32, 32, 3])

In [15]:
(a + b).shape

torch.Size([4, 3, 32, 32])

In [41]:
b=torch.rand(32,8)
a=torch.rand(32,8)
c=torch.stack([a,b,a,b,a,b], dim=0)

for i in c.split(4, dim=0):
    print(i.shape)

print("="*10)    
for i in c.chunk(3, dim=0):
    print(i.shape)

torch.Size([4, 32, 8])
torch.Size([2, 32, 8])
torch.Size([2, 32, 8])
torch.Size([2, 32, 8])
torch.Size([2, 32, 8])


In [43]:
print(
torch.all(torch.eq(a+b, torch.add(a, b))),
torch.all(torch.eq(a-b, torch.sub(a, b))),
torch.all(torch.eq(a*b, torch.mul(a, b))),
torch.all(torch.eq(a/b, torch.div(a, b))),
torch.all(torch.eq(a@b.t(), torch.mm(a, b.t()))),
torch.all(torch.eq(a@b.t(), torch.matmul(a, b.t()))),
sep='\n'
)

tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)


In [50]:
grad = torch.rand(2,3)*15
print(
    grad.min(),
    grad.max(),
    grad.median(),
    grad.clamp(10),
    grad.clamp(0,10),
    sep='\n',
)

tensor(5.7943)
tensor(12.1125)
tensor(8.8097)
tensor([[10.0000, 12.1125, 11.6315],
        [10.0000, 10.0000, 10.9744]])
tensor([[ 5.7943, 10.0000, 10.0000],
        [ 5.8483,  8.8097, 10.0000]])


In [61]:
a=torch.full([8],1.)
b=a.view(2,4)
c=a.view(2,2,2)

print(a,b,c, 
      a.norm(1),
      b.norm(1),
      c.norm(1),      
      a.norm(2),
      b.norm(2),
      c.norm(2),
      b.norm(1, dim=1),
      b.norm(1, dim=0),
      b.norm(2, dim=1),
      c.norm(1, dim=0),
      sep='\n')

tensor([1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor(8.)
tensor(8.)
tensor(8.)
tensor(2.8284)
tensor(2.8284)
tensor(2.8284)
tensor([4., 4.])
tensor([2., 2., 2., 2.])
tensor([2., 2.])
tensor([[2., 2.],
        [2., 2.]])


In [75]:
x=torch.ones(1)
w=torch.full([1],2.)
print(x, w)
mse = F.mse_loss(torch.ones(1), x*w)
print(mse)
print(w.requires_grad_())
mse = F.mse_loss(torch.ones(1), x*w)
print(torch.autograd.grad(mse, [w]))
mse = F.mse_loss(torch.ones(1), x*w)
mse.backward()
print(w.grad)

tensor([1.]) tensor([2.])
tensor(1.)
tensor([2.], requires_grad=True)
(tensor([2.]),)
tensor([2.])


In [122]:
a=torch.rand(3)
a.requires_grad_()
print(a)
p=F.softmax(a,dim=0)

# p[0].backward(retain_graph=True)
# print(a.grad)
p[1].backward(retain_graph=True)
print(a.grad)
p[2].backward(retain_graph=True)
print(a.grad)


p=F.softmax(a,dim=0)

# print(torch.autograd.grad(p[0], [a], retain_graph=True))
g1 = torch.autograd.grad(p[1], [a], retain_graph=True)
print(g1)
g2 = torch.autograd.grad(p[2], [a], retain_graph=True)
print(g2)
print(g1[0]+g2[0])

tensor([0.2576, 0.9601, 0.5049], requires_grad=True)
tensor([-0.1092,  0.2491, -0.1399])
tensor([-0.1785,  0.1092,  0.0693])
(tensor([-0.1092,  0.2491, -0.1399]),)
(tensor([-0.0693, -0.1399,  0.2091]),)
tensor([-0.1785,  0.1092,  0.0693])
